/*
Including this header will disable managed code in a C++ file, even if compiled with the /CLR parameter.
We need to do this with files generated by MIDL.
Otherwise, we get "The Array Bounds Are Invalid" error from at least one RPC call on the x86 platform.
Strangely enough, this hack is not needed on the x64 platform.
*/
#pragma once
#pragma managed(push, off)