name: 🐛 Bug Report
description: Report a bug or unexpected behavior in the DSInternals PowerShell module
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior.
        You can get the last executed commands using: `Get-History | Select-Object -Last 5`
      placeholder: |
        1. Run command '...'
        2. With parameters '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: |
        What actually happened instead.
        Please provide the full error message if applicable. You can get it using: `$Error[0].Exception.Message`
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: stack-trace
    attributes:
      label: Stack Trace
      description: |
        Please provide the full stack trace if applicable.
        You can get it using: `$Error[0].Exception.StackTrace`
      render: text
    validations:
      required: false

  - type: input
    id: dsinternals-version
    attributes:
      label: DSInternals Module Version
      description: |
        Run: `(Get-Module -Name DSInternals -ListAvailable).Version.ToString()`
      placeholder: e.g., 4.14
    validations:
      required: true

  - type: input
    id: powershell-version
    attributes:
      label: PowerShell Version
      description: |
        Run: `$PSVersionTable.PSVersion.ToString()`
      placeholder: e.g., 7.4.0 or 5.1.19041.4412
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System
      description: |
        Run: `(Get-CimInstance -ClassName Win32_OperatingSystem).Caption`
      placeholder: e.g., Microsoft Windows 11 Pro
    validations:
      required: true

  - type: input
    id: dc-version
    attributes:
      label: Target Domain Controller Version
      description: If applicable, specify the Windows Server version of the target domain controller.
      placeholder: e.g., Windows Server 2022
    validations:
      required: false

  - type: dropdown
    id: architecture
    attributes:
      label: Processor Architecture
      description: |
        Run: `$env:PROCESSOR_ARCHITECTURE`
      options:
        - x64
        - x86
        - ARM64
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues to make sure this bug has not already been reported.
          required: true
        - label: I have tested with the latest version of the DSInternals PowerShell module.
          required: true
